import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { ThemeProvider } from "@/components/theme-provider"


export const metadata: Metadata = {
  title: "UMANG PORTFOLIO",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            >
        <div className="relative w-full flex item-center justify-center">
          <Navbar />
        </div>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
